included:
  - RateLimited
  - Tests

excluded:
  - RateLimited.xcodeproj
  - docs

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - force_unwrapping
  - implicit_return
  - sorted_imports
  - vertical_parameter_alignment_on_call

disabled_rules:
  - todo

line_length:
  warning: 140
  error: 180
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 350
  error: 500

file_length:
  warning: 700
  error: 1000

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - q
    - x
    - y

force_unwrapping:
  severity: warning

