name: Bug report
description: Report a problem with RateLimited
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue. Please include enough detail to reproduce it.
  - type: input
    id: version
    attributes:
      label: RateLimited version
      placeholder: 0.1.0
    validations:
      required: false
  - type: input
    id: macos
    attributes:
      label: macOS version
      placeholder: macOS 14.7 / 15.x
    validations:
      required: true
  - type: dropdown
    id: tool
    attributes:
      label: Affected tool
      options:
        - Codex
        - Claude
        - Both
        - UI / Tray
        - Install / Build
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Launch app
        2. Click tray icon
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

